name: Get Peoples Daily
on:
  workflow_dispatch:
#  schedule:
#    - cron: '0 0 * * *'
jobs:
  run:
    runs-on: ubuntu-latest
    name: Get Peoples Daily

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Script
        id: run_script
        run: python main.py --write-github-output

      - name: Create Release and Upload
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create ${{ steps.run_script.outputs.date }} --title ${{ steps.run_script.outputs.date }} --notes "${{ steps.run_script.outputs.release_body }}"
          gh release upload ${{ steps.run_script.outputs.date }} ${{ steps.run_script.outputs.pages_zip_path }}
          gh release upload ${{ steps.run_script.outputs.date }} ${{ steps.run_script.outputs.merged_pdf_path }}
